(function(){
  window.holdingsView=function(){return `<div class="subtitle">保有銘柄</div><div class="card"><table><tr><th>銘柄</th><th>株数</th><th>現在株価</th><th>評価損益</th></tr>${state.holdings.map((h,i)=>{const hp=hasAvg(h)&&hasCurrent(h),q=pl(h),r=pct(h);const ptxt=hp?`${q>=0?"+":"-"}$${f(Math.abs(q))}<br><span class="small">${r>=0?"+":""}${f(r)}%</span>`:"取得単価未設定";return `<tr data-holding="${i}"><td>${escapeHtml(h.name)}</td><td>${h.shares}株</td><td>${hasCurrent(h)?"$"+f(h.current):"未取得"}</td><td>${ptxt}</td></tr>`}).join("")}</table></div><button class="primary" id="updateAllPrices">株価を自動更新</button><button class="secondary" id="addHolding">＋ 銘柄を追加</button>`};
  window.editHolding=function(i){const h=state.holdings[i];if(!h)return;KoBoTrade.detailIndex=i;const q=pl(h),r=pct(h),plText=Number.isFinite(q)?`${q>=0?"+":"-"}$${f(Math.abs(q))}（${r>=0?"+":""}${f(r)}%）`:"取得単価未設定";openModal(`<h2>${escapeHtml(h.name)}</h2><label>取得単価</label><input id="editAvg" type="number" min="0.01" step="0.01" value="${hasAvg(h)?f(h.avg):""}" placeholder="例：228.82"><button class="primary" id="saveHoldingAvg">取得単価を保存</button><div class="row">保有株数　${h.shares}株</div><div class="row">現在株価　<b>${hasCurrent(h)?"$"+f(h.current):"未取得"}</b></div><div class="row">評価損益　${plText}</div><p class="small">現在株価はTwelve Dataから自動取得されます。</p><button class="secondary" id="updateOnePrice">この銘柄の株価を更新</button><button class="secondary danger" id="deleteHolding">保有銘柄から削除</button>`);
    document.getElementById("saveHoldingAvg").onclick=function(){const v=Number(document.getElementById("editAvg").value);if(!Number.isFinite(v)||v<=0){alert("0より大きい取得単価を入力してください");return}state.holdings[i].avg=v;save();editHolding(i)};
    document.getElementById("updateOnePrice").onclick=function(){kobotradeV20UpdateOneHolding(i)};
    document.getElementById("deleteHolding").onclick=function(){if(confirm("この銘柄を削除しますか？")){state.holdings.splice(i,1);save();closeModal();render()}};
  };
  window.addHolding=function(){openModal(`<h2>保有銘柄を追加</h2><label>追加銘柄</label><input id="newName"><label>追加株数</label><input id="newShares" type="number" min="1" value="1"><label>追加購入価格</label><input id="newPrice" type="number" min="0.01" step="0.01"><button class="primary" id="doAddHolding">追加</button>`);document.getElementById("doAddHolding").onclick=function(){const n=document.getElementById("newName").value.trim(),s=Number(document.getElementById("newShares").value),p=Number(document.getElementById("newPrice").value);if(!n||s<=0||p<=0){alert("3項目を入力してください");return}const ex=state.holdings.find(x=>x.name.toLowerCase()===n.toLowerCase());if(ex){const oldS=Number(ex.shares),total=oldS+s;ex.avg=(Number(ex.avg||0)*oldS+p*s)/total;ex.shares=total;ex.current=p}else state.holdings.push({name:n,symbol:kobotradeResolveSymbol(n),shares:s,avg:p,current:p,upActive:false,lastUpPurchasePct:null,downActive:false,lastDownPurchasePct:null,prevPct:null,lastDecisionPct:null,lastDecisionBuy:false,lastDecisionMsg:""});save();closeModal();render()}};
})();
