(function(){
  const KEY="kobotrade_v20_twelvedata_key",LEGACY="kobotrade_twelvedata_key",CACHE_PREFIX="kobotrade_v20_quote_cache_",TTL=15*60*1000;
  window.KoBoTradeStock={symbols:["AAPL","AMZN","COST","GOOG","MAR","MSFT","PM"],prices:{},updatedAt:{}};
  window.kobotradeV20SaveApiKey=function(k){k=String(k||"").trim();if(!k)throw Error("API Keyが空です");localStorage.setItem(KEY,k);localStorage.setItem(LEGACY,k);try{sessionStorage.setItem(KEY,k)}catch(e){}};
  window.kobotradeV20GetApiKey=function(){try{return localStorage.getItem(KEY)||localStorage.getItem(LEGACY)||sessionStorage.getItem(KEY)||sessionStorage.getItem("kobotrade_v19_td_key")||""}catch(e){return""}};
  window.kobotradeV20ClearApiKey=function(){try{localStorage.removeItem(KEY);localStorage.removeItem(LEGACY);sessionStorage.removeItem(KEY)}catch(e){}};
  window.kobotradeV20GetQuoteCacheInfo=function(symbol){try{const c=JSON.parse(localStorage.getItem(CACHE_PREFIX+String(symbol).toUpperCase())||"null");if(!c)return null;return{price:+c.price,savedAt:+c.savedAt,expiresAt:+c.savedAt+TTL,remainingMs:Math.max(0,+c.savedAt+TTL-Date.now())}}catch(e){return null}};
  async function raw(symbol){const key=kobotradeV20GetApiKey();if(!key)throw Error("Twelve Data API Keyが未設定です");const url="https://api.twelvedata.com/price?symbol="+encodeURIComponent(symbol)+"&apikey="+encodeURIComponent(key);const res=await fetch(url);const data=await res.json();if(!res.ok||data.status==="error"||data.code)throw Error(data.message||("HTTP "+res.status));const p=Number(data.price);if(!Number.isFinite(p))throw Error("価格データが取得できませんでした");return p}
  window.kobotradeV20FetchPrice=async function(symbol){symbol=String(symbol||"").toUpperCase();const info=kobotradeV20GetQuoteCacheInfo(symbol);if(info&&info.remainingMs>0){KoBoTradeStock.prices[symbol]=info.price;KoBoTradeStock.updatedAt[symbol]=info.savedAt;return info.price}const p=await raw(symbol),savedAt=Date.now();KoBoTradeStock.prices[symbol]=p;KoBoTradeStock.updatedAt[symbol]=savedAt;try{localStorage.setItem(CACHE_PREFIX+symbol,JSON.stringify({price:p,savedAt}))}catch(e){}return p};
  window.kobotradeV20UpdateOneHolding=async function(i){const h=state.holdings[i];if(!h)return;try{const symbol=h.symbol||kobotradeResolveSymbol(h.name),p=await kobotradeV20FetchPrice(symbol);h.symbol=symbol;h.current=p;save();editHolding(i);alert("株価を更新しました。\n$"+f(p))}catch(e){alert("株価取得失敗: "+e.message)}};
  window.kobotradeV20UpdateHoldingsPrices=async function(){if(!kobotradeV20GetApiKey()){alert("Twelve Data API Keyを先に設定してください。");return}let failed=[];for(const h of state.holdings){try{const s=h.symbol||kobotradeResolveSymbol(h.name);h.symbol=s;h.current=await kobotradeV20FetchPrice(s)}catch(e){failed.push(h.name)}}save();render();alert(failed.length?"取得できなかった銘柄: "+failed.join(", "):"株価更新完了")};
})();
